library(tm);library(wordcloud);library(memoise);library(dplyr)
getTermMatrix <- memoise(function() {
        tweets <- read.csv("tweets.csv", stringsAsFactor = FALSE)
        tweets <- tbl_df(tweets)
        tweets <- select(tweets, interaction.content)
        names(tweets) <- c("text")
        tweets <- gsub("(f|ht)(tp)(s?)(://)(.*)[.|/](.*)", "", tweets$text)
        tweets <- as.data.frame(tweets)
        myCorpus <- Corpus(VectorSource(tweets$tweets))
        myCorpus <- tm_map(myCorpus, content_transformer(tolower))
        myCorpus <- tm_map(myCorpus, removePunctuation)
        myStopwords <- c(stopwords("english"), "tflbusalerts", "mayoroflondon", "tflofficial", "tfltrafficnews","tflwaystopay", "viajeramlg","franbig","debbiepj10", "halshinnie", "bus")
        myCorpus <- tm_map(myCorpus, removeWords, myStopwords)
        myCorpusCopy <- myCorpus
        myCorpus <- tm_map(myCorpus, stemDocument)
        tdm <- TermDocumentMatrix(myCorpus, control = list(wordLengths = c(1, Inf)))
        m <- as.matrix(tdm)
        sort(rowSums(m), decreasing = TRUE)
})
